### ISSUE TITLE
Sensor to trigger send Midi Data via MIDI USB

### ISSUE THREAD

**Issue by Kokuko3** [BoffinFactory/PianoStaircase#13]
Working on wiring up one sensor to send a Midi note when triggered

**Comment by Kokuko3** [comment]
Using the hc-sr04 sample code as an initial test

**Comment by KalenTullis** [comment]
Updated code is posted in MIDIFromSensor directory in dev-kbab. Code is setup for IR sensor at the time of upload, but performed better with a ultrasonic sensor. I also think it would work well with a ToF sensor and 2 ToF sensors easily.
