### ISSUE TITLE
Trigger MIDI note with Time of Flight sensor

### ISSUE THREAD

**Issue by mkijowski** [BoffinFactory/PianoStaircase#26]
just do it :p

Key takeaways, begin controlling MIDI with ToF (working on implementation).

Next step will be control 2 midi notes with 2 time of flight sensors

**Comment by ReeseHatfield** [comment]
Check out [this](https://github.com/BoffinFactory/PianoStaircase/tree/MultiToFSensors) branch for current development.  As of March. 29 we "sorta" have multi  (>2) sensor input reading up to about 0.8 meters
