### ISSUE TITLE
Piano Library

### ISSUE THREAD

**Issue by JakeHamblin** [BoffinFactory/PianoStaircase#45]
@mkijowski suggested we should do a library built off of #44. I'm going to build a library to support this note support that can be used for ToF and ultrasonic.

**Comment by mkijowski** [comment]
So making an assumption about this library creating a bollean array of state values (midi note is on or off).

* method to check state of all notes
* method to check state of one note
* method to compare state of one note

**Comment by mkijowski** [comment]
compare state should trigger a MIDI event on a state change (either note on or note off depending)

**Comment by JakeHamblin** [comment]
@mkijowski Rather than doing the library with those methods, why not just do a single method that does a state change. Provide the note and what state you want it to be in. If it's already in that state, we don't need to do anything. Otherwise, make the change with a MIDI event and update the state in the array. Just trying to streamline the usage of the library a little
