### ISSUE TITLE
PIano - Sound Control with Pi

### ISSUE THREAD

**Issue by pattonsgirl** [BoffinFactory/PianoStaircase#5]
Use Raspberry Pi to play select sounds

**Comment by mkijowski** [comment]
We need to figure out what synth (fluidsynth?) and how to configure...

I've started looking into the following:
http://jacquespi.blogspot.com/2013/07/synthesizer.html
https://www.arduino.cc/reference/en/libraries/midiusb/

**Comment by ReeseHatfield** [comment]
I was able to get [fluidsynth](https://www.fluidsynth.org/) to work on Ubuntu 22.04. 
Using [these](https://archive.org/download/free-soundfonts-sf2-2019-04) and [these](https://github.com/buddyjojo/meme-soundfonts) soundsfonts. With [these](http://www.midishrine.com/index.php?id=170) midi files
</br>
Example:
```bash
fluidsynth --audio-driver=pulseaudio --gain 10 --dump --verbose Downloads/yippe.sf2 Downloads/level1.mid

```

**Comment by mkijowski** [comment]
Thanks @ReeseHatfield !
Should any of these links be put in the repo somewhere?

**Comment by mkijowski** [comment]
Note, I propose we close this issue after we update some of the documentation per Reese's comment.

**Comment by ReeseHatfield** [comment]
> Thanks @ReeseHatfield !
> 
> Should any of these links be put in the repo somewhere?

Probably yeah. At least the fluidsynth docs. If I get time (or procrastinate my other things), I would like to get audio to play in the same manner we want to interface with the sensors. There is a [python fluid synth](https://pypi.org/project/pyFluidSynth/) api we could use assuming me are using python for that.

Or if we are feeling extra lazy just run the fluid synth cli as a system command with the 'subprocess' module trivially.

**Comment by ReeseHatfield** [comment]
> Thanks @ReeseHatfield !
> 
> Should any of these links be put in the repo somewhere?

Probably yeah. At least the fluidsynth docs. If I get time (or procrastinate my other things), I would like to get audio to play in the same manner we want to interface with the sensors. There is a [python fluid synth](https://pypi.org/project/pyFluidSynth/) api we could use assuming me are using python for that.

Or if we are feeling extra lazy just run the fluid synth cli as a system command with the 'subprocess' module trivially.

**Comment by BPennie03** [comment]
Closing as per Matt's request, as the documentation has already been updated/merged
